### ISSUE TITLE
mvn clean doesn't remove build directory

### ISSUE THREAD

**Issue by wieck** [pgsql-io/benchmarksql#11]
executing `mvn clean` only removes the `target` directory, not `build`. The usual expectation is that it does in order to force a full recompile of all source code.

**Comment by angoca** [comment]
I think the `build` directory is created by another tool, but not the Maven lifecycle process. 
It could be related to some residual Ant task, like the Docker creation (or another, I am not sure about which tool exactly).
Maven by default does not manipulates other directories that `target`.

Anyway, the `build` directory is ignored by git (`.gitignore`) and this won't be include in this code.

Regarding to this `build` directory, we have to update the documents (under `/doc` to update the Building process).

**Comment by wieck** [comment]
It was indeed some leftovers from Ant.

Will remove build and dist from .gitignore.

And yes, we have a lot of /doc work to do. 

Thanks
